module.exports = {
  LINK_ALREADY_EXISTS: 2,
  NOT_AUTHORIZED: 4,
  TRACK_LENGTH_EXCEEDED: 5,
  LINK_LENGTH_EXCEEDED: 6,
  OUT_OF_TRACKS: 3,
  COMPETITION_RESET: 7,
  MAX_NUM_TRACKS_EXCEEDED: 8,
  UNSUPPORTED_FILE_TYPE: 9,
  MAX_FILE_SIZE_EXCEEDED: 10,
  TRACK_LENGTH_NOT_MET: 11,
};
